[dependencies]
base = "0.16.0"
core = "2.1.0"
icrc1-mo = "0.2.1"
icrc2-mo = "0.2.1"
icrc3-mo = "0.4.3"
icrc4-mo = "0.2.1"
icrc75-mo = "../ICRC75"
ovs-fixed = "0.2.2"
stable-write-only = "0.2.1"
sha2 = "0.1.12"
candy = "0.3.1"
stableheapbtreemap = "1.5.0"
principal-ext = "0.1.0"
timer-tool = "0.2.1"
ic-certification = "1.1.0"
class-plus = "0.2.1"
star = "0.1.1"
vector = "0.4.2"

[dev-dependencies]
test = "2.1.2"
fuzz = "1.0.0"
matchers = "2.1.0"

[toolchain]
moc = "1.1.0"

[package]
name = "ovs-ledger"
version = "0.0.1"
description = "Manages open value sharing for canisters"
repository = "https://github.com/icdevsorg/ovs-ledger"
keywords = [
  "icrc2",
  "icrc1",
  "icrc3",
  "icrc4",
  "icrc10",
  "fungible",
  "token",
  "standard",
  "cycles",
  "open value sharing"
]
